services:
  - type: web
    name: crew-devteam-1
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_API_TOKEN
        sync: false
      - key: RENDER_API_KEY
        sync: false
    autoDeploy: true 